[workspace]
resolver = "2"
members = [
    "packages/components",
    "packages/web",
    "packages/desktop",
    "packages/mobile",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde_json = "1"
base64 = "0.23.1"
wasm-bindgen = "=0.2.127"
dioxus = { version = "0.7.1" }
serde = { version = "1", features = ["derive"] }

components = { path = "packages/components" }

[profile.release]
opt-level = "z"
lto = true
