//! Web entry point: launch, load this package's Tailwind output, and
//! provide the browser-specific bits. All UI lives in `components`.

use components::{App as SharedApp, PlatformServices};
use dioxus::prelude::*;

// Generated by the Tailwind CLI that `dx` runs for this package
// (input: ../tailwind.css, output: assets/tailwind.css).
const TAILWIND_CSS: Asset = asset!("/assets/tailwind.css");

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    use_context_provider(|| PlatformServices { open_external });

    rsx! {
        document::Stylesheet { href: TAILWIND_CSS }
        SharedApp {}
    }
}

/// Same tab, like the old boot menu did, so visitors never lose the page.
fn open_external(url: &str) {
    if let Some(window) = web_sys::window() {
        let _ = window.open_with_url_and_target(url, "_self");
    }
}
