[web.wasm.opt]
debug = false
level = "z"

[web.app]
# title = "The Typographic Journal"
base_path = "tquilla.is-a.dev/journal-typographic"

[application]
name = "journal"
default_platform = "web"

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true

# [web.resource]
# style = []
# script = []
